### ISSUE TITLE
images not showing after build

### ISSUE THREAD

**Issue by Anaraquelpengelly** [fhiegel/slide-template#1]
Hi, 

I have added images to my pitch using html, but somehow, when I build the site, the images no longer appear.  Here is how the pitch md looks like:

```
 ---
 
  ### Before we start, a survey...

 <img title="survey" src=mentimeter_q0.png  width="300" height="300">

 ---
```

**Comment by fhiegel** [comment]
Hello,

I cannot reproduce the issue you encounter :
- I added a slide with an image
- deployed here : https://fhiegel.github.io/slide-template/pitch/#/3

Where did you encounter the issue ? On localhost ? On deployed website ?
Did you update the `site_url` with relative path, in your `mkdocs.yml` ?

**Comment by Anaraquelpengelly** [comment]
hi, thanks very much for your reply! I encounter the problem when I do the build 

` mkdocs build` 

after I get a site folder and the html produced there does not have images and I somehow cannot make the images appear even if I change the folder of the html.
Do you not use build to get your website? 
how did you host the site on github?  just with your repo?
Thanks again!

**Comment by fhiegel** [comment]
Hi,

`mkdocs build` is done during the pipeline execution. I recently switch from Travis (described in `.travis.yml`) to  Github Actions (in `.github/workflows/gh-pages.yml`) and both targets a GitHub Pages (hosting my repository). 

I tried to reproduce the bug  :
- `mkdocs serve` on my local workspace : no problem encountered
- `mkdocs build` on my local workspace : no problem encountered when `mkdocs.yml` is properly configured (and open it from my IDE, because open site folder directly from a browser won't work)
- deployed on GitHub Pages with pipeline : no problem encountered: have a look [here](https://fhiegel.github.io/slide-template/pitch/#/3)

What is the value of the following section in your `index.html` in your `site` folder?
```
<link rel="canonical" href="???">
```

**Comment by Anaraquelpengelly** [comment]
thangs for looking into this, so, what do you mean by `mkdocs.yml` properly configured?

could you tell me how you deploy on github pages? do you just create a page and then add that in `mkdocs.yml` ?

at the moment the value for the `site` `index.html` is 

```
<link rel="canonical" href="https://example.com/">

```

so it is the same ad the `url` in the `mkdocs.yml` file.  It is just a dummy. Since I don't actully have a site yet. This why it would be amazing if you could direct me to how to create a github website like you made.

**Comment by fhiegel** [comment]
> It is just a dummy.

=> This is why you don't have your image on local build.
To build site on local, you should configure url to a local server. Don't do that : it is a waste of time. For local purpose, juste use `mkdocs serve`.

>  This why it would be amazing if you could direct me to how to create a github website like you made.

=> Follow that way
- Have a look on GitHub Pages : https://pages.github.com
- configure your GitHub repository according to GitHub Pages
- configure `mkdocs.yml` with proper url (something like http//username.github/your_repo)
- Push on master. Wait the pipeline to build and deploy. Go on previous url.

**Comment by Anaraquelpengelly** [comment]
Hi, 

Thanks so much for your reply! I have now managed to deploy the slides with github pages. 😄  ! 

Have a great weekend!
